- name: Configure my workstantion
  hosts: ubuntu_22  # Specify the target hosts or groups
  # become: true  # If the role requires elevated privileges
  
  roles:
    - role: ansible-role-oh-my-zsh-p10k-master  # Name of the role to be executed
      vars:
        users:
            - username: devops
